name: Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: bartveneman/project-wallace-github-action@master
        with:
          project_wallace_token: "{{ secrets.PROJECT_WALLACE_WEBHOOK_TOKEN }}"
