name: Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Build CSS"
        run: mkdir build && echo 'a{}' > build/style.css
      - name: "Get CSS Analytics diff"
        run: curl http://www.mocky.io/v2/5d73669d3300000f000817c5 -X POST -d @build/style.css
      - name: Print env
        run: |
          echo HOME         ${HOME}
          echo GITHUB_ACTOR ${GITHUB_ACTOR}
          echo GITHUB_REPOSITORY ${GITHUB_REPOSITORY}
          echo GITHUB_SHA ${GITHUB_SHA}
