name: Publish to Project Wallace
author: Bart Veneman
description: Push your CSS to Project Wallace for analysis
inputs:
  project_wallace_token:
    description: The Webhook Token from your Project Wallace project
    required: false
    default: ""
branding:
  color: green
  icon: trending-up

on:
  push:
    branches:
      - master

jobs:
  report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: "Use Node ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Report CSS to Project Wallace
        run: |
          npm ci
          npm run build
          curl https://www.projectwallace.com/webhooks/v1/imports?token=${{secrets.PROJECT_WALLACE_WEBHOOK_TOKEN}} \
            --request POST \
            --header 'Content-Type: text/css' \
            --data @build/style.css
